parser: "babel-eslint"
plugins: ["react"]
extends: "airbnb"
env:
  es6: true
rules:
  # Allow for aligned import statments.
  no-multi-spaces:
    - 1
    - exceptions:
        "ImportDeclaration": true
  # Force objects declarations to be aligned.
  key-spacing:
    - 1
    - align: "value"
